### ISSUE TITLE
Library method/class documentation

### ISSUE THREAD

**Issue by brianmichel** [cedexis/RadarKit#6]
Documentation on the methods and classes in the library would be super helpful for people consuming the library to be able to click on a method and see what exactly a property is, or any kind of notes associated with that.

Also if the code were completely documented, it could be used to generate documentation for the library that could easily be distributed. Please take a look at Apple's guidelines [here](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/HeaderDoc/usage/usage.html).

There is also a good post on SO regarding different formatting and where/how it shows up in Xcode, http://stackoverflow.com/questions/19168423/what-are-the-new-documentation-commands-available-in-xcode-5/19169271#19169271

**Comment by javorosas** [comment]
Resolved in b0793511e9e4ec35bb0fc50514f536a9b732ad03
