### ISSUE TITLE
Use nullability qualifiers to facilitate easier Swift usage

### ISSUE THREAD

**Issue by brianmichel** [cedexis/RadarKit#7]
Marking parameters and return types with nullability qualifiers will help developers consume this library in Swift as well. 

Here's a great blog post describing how these new qualifiers work, https://developer.apple.com/swift/blog/?id=25.

**Comment by javorosas** [comment]
There is no need to add those, since the only parameters required by the library are native C types Int32, and Nullability specifiers can only be added to pointer types.

**Comment by javorosas** [comment]
My bad. There are two arguments that might be nullable:
- The Completion handler (a block) when specified
- The Protocol (NSString) when specified

**Comment by javorosas** [comment]
Resolved in 36f48c4407a67438cf539987e46cdd346c0f258f
